const newArticleStrings = {
    al: {
        header: 'Ploteso fushat per te publikuar nje artikull te ri',
        albanian: 'Shqip',
        english: 'Anglisht',
        italian: 'Italisht',
        publish: 'Ngarko Artikullin',
        required: 'Fusha e detyrueshme',
        title: 'Titulli',
        body: 'Teksti',
        tagAvailable: 'Gjithe tag-et',
        tagChoosen: 'Tag-et e zgjedhur',
        addOne: 'Zgjidh 1 tag per te vazhduar',
        addLimit: 'Maksimumi 3 tag te lejuar',
        noPublish: 'Ngarko artikullin pa e publikuar',
        addMedia: 'Ngarko Foto',
        filesSelected: 'File te zgjedhura:',
        mainPage: 'Vendos artikullin ne faqe te pare',
        success: 'Artikulli u ngarkua me sukses',
        err: 'Kerkesa nuk u plotesua. Provo me vone'
    },
    it: {
        header: 'Compila tutti i campi per pubblicare un nuovo articolo',
        albanian: 'Albanese',
        english: 'Inglese',
        italian: 'Italiano',
        publish: 'Carica Articolo',
        required: 'Campo necessario',
        title: 'Titolo',
        body: 'Testo',
        tagAvailable: 'Tutti i tag',
        tagChoosen: 'Tag scelti',
        addOne: 'Scegli almeno 1 tag per continuare',
        addLimit: 'Massimo 3 tag permessi',
        noPublish: `Carica l'articolo senza pubblicarlo`,
        addMedia: 'Inserisci foto',
        filesSelected: 'File selezionati:',
        mainPage: 'Inserire l`articolo nella pagina principale',
        success: 'Articolo inserito correttamente',
        err: 'Richiesta non riuscita. Prova piu tardi'
    },
    en: {
        header: 'Fill in all fields to publish a new article',
        albanian: 'Albanian',
        english: 'English',
        italian: 'Italian',
        publish: 'Publish Article',
        required: 'Field is required',
        title: 'Title',
        body: 'Body',
        tagAvailable: 'All tags',
        tagChoosen: 'Chosen tags',
        addOne: 'Add at least 1 tag to continue',
        addLimit: 'Maximum 3 tags allowed',
        noPublish: 'Upload article without publishing',
        addMedia: 'Add photos',
        filesSelected: 'Selected files:',
        mainPage: 'Add article in main page',
        success: 'Article uploaded correctly',
        err: 'Request not completed. Try again later'
    }
}

export { newArticleStrings };